{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pavel-argocd.serviceAccountName" . }}
  labels:
{{ include "pavel-argocd.labels" . | nindent 4 }}
{{- end -}}
